  dev[m
* [32mfeature/powerups/reversePaddleControls[m
  feature/powerups/shrinkPaddleSize[m
  main[m
  [31mremotes/origin/HEAD[m -> origin/dev
  [31mremotes/origin/bugfix/delay-for-animation[m
  [31mremotes/origin/dev[m
  [31mremotes/origin/ehc/socket-connection-recovery[m
  [31mremotes/origin/feature/PongScoreBoard[m
  [31mremotes/origin/feature/host-lobby-ux-improvements[m
  [31mremotes/origin/feature/login-page-error-bar[m
  [31mremotes/origin/feature/pong-smoothing[m
  [31mremotes/origin/feature/powerup-component[m
  [31mremotes/origin/feature/powerup-spawn[m
  [31mremotes/origin/feature/powerups/shrinkPaddleSize[m
  [31mremotes/origin/feature/rps-timer[m
  [31mremotes/origin/feature/rps-timer-fixed[m
  [31mremotes/origin/feature/timer[m
  [31mremotes/origin/main[m
