name: Deploy backend

on:
  push:
    branches: ['main']

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Shazam-3-Scrum-Unleashed/server
            git pull origin main
            docker compose down
            docker compose up --build -d